# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['entry_point.py'],
    pathex=[],
    binaries=[],
    datas=[('dlp_agent', 'dlp_agent')],
    hiddenimports=[
        'easyocr',
        'easyocr.easyocr',
        'torch',
        'torchvision',
        'PIL',
        'PIL.Image',
        'cv2',
        'numpy',
        'scipy',
        'skimage',
        'yaml',
        'requests',
        'urllib3',
        'charset_normalizer',
        'docx',
        'PyPDF2',
        'openpyxl',
        'pptx',
        'click',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='entry_point',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
